/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список всех предстоящих бронирований по всем типам событий,
         *     отсортированный по startTime. Доступно только владельцу календаря.
         */
        get: operations["Bookings_list"];
        put?: never;
        /**
         * @description Создать бронирование выбранного слота. Публичный эндпоинт для гостя.
         *     Возвращает cancellationToken, который гость должен сохранить,
         *     чтобы позже отменить свою бронь без аутентификации.
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Отменить бронирование от имени владельца календаря.
         *     Не требует cancellationToken.
         */
        post: operations["Bookings_cancelByOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/guest-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Отменить своё бронирование от имени гостя.
         *     Требует cancellationToken, выданный при создании брони.
         */
        post: operations["Bookings_cancelByGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список всех типов событий. Публичный эндпоинт — гость видит
         *     название, описание и длительность, чтобы выбрать тип бронирования.
         */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события. Доступно только владельцу календаря. */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные и занятые слоты для конкретного типа события на
         *     BOOKING_WINDOW_DAYS (14) дней вперёд, начиная с текущей даты.
         *     Занятость учитывает бронирования всех типов событий
         *     (правило: на одно и то же время нельзя создать две записи).
         *     Публичный эндпоинт.
         */
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить один тип события по id. Публичный эндпоинт. */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        /**
         * @description Удалить тип события. Доступно только владельцу.
         *     Существующие бронирования по этому типу НЕ удаляются и НЕ блокируют
         *     удаление — они хранят снэпшот name/durationMinutes и продолжают
         *     отображаться в списке встреч владельца.
         */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Частично обновить тип события. Доступно только владельцу. */
        patch: operations["EventTypes_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Стандартная модель ошибки API */
        ApiError: {
            code: string;
            message: string;
        };
        /**
         * @description Бронирование гостем свободного слота одного из типов событий.
         *     Гость создаёт бронь без аккаунта, поэтому имя/email фиксируются
         *     прямо в записи, а отмена своей брони гостем выполняется по
         *     cancellationToken, а не по авторизации.
         */
        Booking: {
            id: string;
            /**
             * @description Ссылка на тип события. Может быть null, если исходный EventType
             *     был позже удалён владельцем — при этом сама бронь не пропадает
             *     (см. EventTypeName/durationMinutes-снэпшот ниже).
             */
            eventTypeId: string | null;
            /** @description Снэпшот названия типа события на момент создания брони */
            eventTypeName: string;
            /**
             * Format: int32
             * @description Снэпшот длительности (в минутах) на момент создания брони
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Начало забронированного интервала
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Конец интервала: startTime + durationMinutes
             */
            endTime: string;
            guestName: string;
            guestEmail: string;
            status: components["schemas"]["BookingStatus"];
            /** @description Причина отмены, если статус cancelled */
            cancellationReason?: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для отмены бронирования */
        BookingCancel: {
            cancellationReason?: string;
        };
        /** @description Данные для создания бронирования гостем */
        BookingCreate: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Должен попадать в окно [now, now + BOOKING_WINDOW_DAYS]
             */
            startTime: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
        };
        /**
         * @description Ответ на создание брони — единственный момент, когда возвращается
         *     cancellationToken. Гость должен сохранить его, чтобы отменить бронь
         *     без аутентификации.
         */
        BookingCreateResult: {
            id: string;
            /**
             * @description Ссылка на тип события. Может быть null, если исходный EventType
             *     был позже удалён владельцем — при этом сама бронь не пропадает
             *     (см. EventTypeName/durationMinutes-снэпшот ниже).
             */
            eventTypeId: string | null;
            /** @description Снэпшот названия типа события на момент создания брони */
            eventTypeName: string;
            /**
             * Format: int32
             * @description Снэпшот длительности (в минутах) на момент создания брони
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Начало забронированного интервала
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Конец интервала: startTime + durationMinutes
             */
            endTime: string;
            guestName: string;
            guestEmail: string;
            status: components["schemas"]["BookingStatus"];
            /** @description Причина отмены, если статус cancelled */
            cancellationReason?: string;
            /** Format: date-time */
            createdAt: string;
            cancellationToken: string;
        };
        /**
         * @description Статус бронирования. Отмена не удаляет запись физически.
         * @enum {string}
         */
        BookingStatus: "accepted" | "cancelled";
        /**
         * @description Тип события. Создаётся и управляется владельцем календаря
         *     (единственный предзаданный профиль, без регистрации/авторизации).
         */
        EventType: {
            id: string;
            name: string;
            description: string;
            /**
             * Format: int32
             * @description Длительность события в минутах, должна быть положительной
             */
            durationMinutes: number;
        };
        /** @description Данные для создания типа события */
        EventTypeCreate: {
            name: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Данные для частичного обновления типа события */
        EventTypeUpdate: {
            name?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        /** @description Свободный/занятый интервал в календаре типа события (вычисляемая сущность) */
        Slot: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            isAvailable: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCreateResult"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_cancelByOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCancel"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_cancelByGuest: {
        parameters: {
            query: {
                cancellationToken: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCancel"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
